# Generated by Django 2.1.7 on 2019-03-15 15:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_statement', django.contrib.postgres.fields.jsonb.JSONField()),
                ('private_key', models.BinaryField(null=True)),
                ('token', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('signed', models.DateTimeField(null=True)),
            ],
        ),
    ]
