# Generated by Django 2.1.7 on 2019-03-20 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationrequest',
            name='certified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificationrequest',
            name='signed',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='certificationrequest',
            name='token',
            field=models.TextField(editable=False, null=True),
        ),
    ]
